### ISSUE TITLE
auth_on_subscribe, auth_on_publish not being called.

### ISSUE THREAD

**Issue by dechaoqiu** [erlio/vmq_webhooks#1]
Hi,
After a quick test following the README, it seems like neither `auth_on_subscribe` nor `auth_on_publish` are being called. I am using `Paho.MQTT.Client`.

```
client = new Paho.MQTT.Client(location.hostname, 8083, "web_" + parseInt(Math.random() * 100, 10));
client.subscribe('test_topic');
```

**Comment by dergraf** [comment]
Hi there
Have you disabled the vmq_acl/vmq_passwd plugins?
Best
Andre

**Comment by dechaoqiu** [comment]
Thanks for your immediate reply. I disabled `vmq_passwd`, but not `vmq_acl`. `auth_on_subscribe` and `auth_on_publish` both got triggered after I disabled `vmq_acl`.

Thanks
