### ISSUE TITLE
Webhooks Compilation Failure

### ISSUE THREAD

**Issue by odx-tech** [erlio/vmq_webhooks#12]
Hi,

We are trying to compile the webhooks to include in vmq. We've been getting the following error:

===> Verifying dependencies...
===> Compiling vmq_webhooks
===> Compiling src/vmq_webhooks_cli.erl failed
src/vmq_webhooks_cli.erl:38: syntax error before: '{'
src/vmq_webhooks_cli.erl:70: syntax error before: '{'

src/vmq_webhooks_cli.erl:31: function b64opt/1 undefined
src/vmq_webhooks_cli.erl:53: function get_opts/1 undefined

Can you please advise us on how to proceed ? 

Thanks,
Karthik

**Comment by odx-tech** [comment]
Got it resolved, sorry for the Issue.

**Comment by rolandvar** [comment]
@odx-tech I have the same error, how did you solve it? Thank you!

**Comment by odx-tech** [comment]
We were using an older version of Erlang causing the compilation error. This was fixed on using the recommended version of Erlang (19+)


Thanks,
Karthik

**Comment by larshesel** [comment]
Hi, just to be clear, `vmq_webhooks` works with both erlang 18 and 19. An important thing to know is that the Erlang version used to compile VerneMQ itself needs to be the same (or newer) than the one used to compile `vmq_webhooks`. For the VerneMQ packages we currently use Erlang 18.
