### ISSUE TITLE
Validation for vmq_webhooks.conf missing

### ISSUE THREAD

**Issue by michikuehne** [erlio/vmq_webhooks#13]
Hey there,

The following incorrect vmq_webhooks.conf will be processed by vmq_webhook plugin but not by vernemq it self.
`{hooks,1,
 [
   {"http://localhost/api/auth/register", auth_on_register, [{base64_payload, true}]},
   {"http://localhost/api/auth/subscribe", auth_on_subscribe, [{base64_payload, true}]},
   {"http://localhost/api/auth/publish", publish, [{base64_payload, true}]}
 ]}.`

The webhook "publish" doesn't exist. However the vmq-admin webhooks status shows
`+-----------------+-----------------------------------+-------------+

|      hook       |             endpoint              |base64payload|

+-----------------+-----------------------------------+-------------+

|auth_on_subscribe|http://localhost/api/auth/subscribe|    true     |

|auth_on_register |http://localhost/api/auth/register |    true     |

| auth_on_publish | http://localhost/api/auth/publish |    true     |

+-----------------+-----------------------------------+-------------+`

But publish webhook won't get into the vmq_plugin.conf.
`{plugins,[{application,vmq_passwd,[]},
          {application,vmq_acl,[]},
          {module,vmq_config,[{hooks,[{change_config,change_config,1}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_write,msg_store_write,2}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_delete,msg_store_delete,2}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_find,msg_store_find,1}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_read,msg_store_read,2}]}]},
          {application,vmq_webhooks,
                       [{paths,["/app/broker/plugins/vmq_webhooks/_build/default/"]}]},
          {module,vmq_webhooks_plugin,
                  [{hooks,[{auth_on_register,auth_on_register,5}]}]},
          {module,vmq_webhooks_plugin,
                  [{hooks,[{auth_on_subscribe,auth_on_subscribe,3}]}]}]}.`

I think there's some additional validation inside of the vmq_webhooks plugin necessary.

Best,
Michael

**Comment by larshesel** [comment]
Hi, have you been editing the `vmq_webhooks.conf` file by hand? It shouldn't be possible to add a webhooks with a non-existing plugin hook like `publish` when using the `vmq-admin` tool. I suspect some changes were done to the file behind the back of `vmq_webhooks` which would then not pick up the changes. Could you completely restart VerneMQ and see what is then reported using `vmq-admin webhooks status`, paste the contents of `vmq_webhooks.conf` and `vmq_plugin.conf`?

**Comment by michikuehne** [comment]
Yes, I edit the vmq_webhooks.conf by hand cause I load my custom conf during the docker startup.
You've guessed right.
vmq-admin webhooks register hook=publish endpoint="http://localhost"
results `Invalid value: "publish"`

I placed the vmq_webhooks.conf here: /app/broker/plugins/vmq_webhooks/_build/default/lib/vmq_webhooks/priv/vmq_webhooks.conf

After restart VerneMQ the output, which I posted above, looks still the same.
I think the vmq_webhooks plugin loads the conf without validating it.

**Comment by larshesel** [comment]
Since we're integrating everything into the `vernemq.conf` file this issue is no longer relevant. Closing.
