### ISSUE TITLE
Saving webhooks on stop, loading webhooks on start

### ISSUE THREAD

**Issue by vladbabii** [erlio/vmq_webhooks#4]
Right now, after I register some webhooks then stop then start vernemq the registered hooks dissapear.
Is there any place I can set the webhooks to automatically re-attach after start?

**Comment by larshesel** [comment]
Hi @vladbabii thank for using VerneMQ and VerneMQ webhooks. We do not yet support persisting the registered hooks and we are considering what would be the best way to solve this. We need to solve this for the vmq_diversity plugin as well, so we have to come up with a general solution. It's unclear at the moment when we'll be tackling this.

**Comment by larshesel** [comment]
Hi @vladbabii basic support for persisting webhooks via the `priv/vmq_webhooks.conf` file has been added in the 0.2.0 version. See the changelog.md for details as there are a number of changes that can affect existing webhooks.

I hope you can use this feature.

**Comment by vladbabii** [comment]
Thank you very much!, I'll deploy and test next week
