### ISSUE TITLE
Payload format

### ISSUE THREAD

**Issue by diegobes** [erlio/vmq_webhooks#5]
Hi;
The messages we use are all binary ( protobuf v3 ).
the on_publish and on_deliver hooks presents the payload in the Post request as a json field "payload".
How this will work with binary payloads ?
( I sent a similar questionn to the main repository )

Thanks

**Comment by larshesel** [comment]
Hi - thanks for bringing this issue up - to be honest it's an oversight on my part and your suspicion is entirely correct: the current code cannot handle arbitrary binary payloads, only the subset that consists of utf8 encoded strings.

As you mentioned in erlio/vernemq#210 the payload would have to be base64 encoded to be a valid json structure - so to support this I suppose we should automatically base64 encode the payload data and let the webhook implementors decode it. This would of course be a breaking change for existing users of the webhooks plugin but I think a necessary one. What do you think @dergraf ?

**Comment by dergraf** [comment]
Could we detect if the payload is UTF-8 encoded and pass it as a String or base64 encode it if required?

Another option would be to make some encoders configurable.

**Comment by larshesel** [comment]
@dergraf I don't think automatic detection would be a good idea. It would be expensive to do and also it would be confusing for the clients to handle.

I think the only real way forward is to base64 encode by default and maybe add a way to disable it for those that don't need it (which is probably a special case).
