### ISSUE TITLE
Subscriber_id modifier with auth_on_register hook is not applied

### ISSUE THREAD

**Issue by tpuza** [erlio/vmq_webhooks#6]
We have business rule to enforce same username and clientId when MQTT client connects to prevent client takeover. VerneMQ  does not have this feature in global config, so we decided to implement it using webhooks.

So for auth_on_register hook we do "ok" response message with the subscriber_id modifier as following:

```
{"result":"ok","modifiers":{"subscriber_id":"xxx"}}
```

where "xxx" equeals to the username.

Issues is that subscriber_id is not modified and flow continues with the original subscriber_id.

**Comment by ioolkos** [comment]
Hi @tpuza OK, thanks for this!

@dergraf actually, is there a shortcut how we could enforce username = clientID?
@larshesel this is maybe the same discussion we had lately on modifications within a hook's flow?

**Comment by larshesel** [comment]
Hi @tpuza, sorry for the long delay. I think I've confirmed this to be a but in VerneMQ itself, see erlio/vernemq#235.

Did you find a workaround in the meantime? One way would be to reject any clients where the username is not equal to the clientid.

**Comment by tpuza** [comment]
Hi @larshesel, yeap we did it exactly that way you mention.

**Comment by larshesel** [comment]
This was fixed in erlio/vernemq#235
