### ISSUE TITLE
Received payload is not JSON error on "on_publish" hook

### ISSUE THREAD

**Issue by tpuza** [erlio/vmq_webhooks#7]
Here in docs [https://github.com/erlio/vmq_webhooks#on_publish](https://github.com/erlio/vmq_webhooks#on_publish) is stated, that response should be empty.

When we return empty response, plugin throws an error
`[error] <0.388.0>@vmq_webhooks_plugin:call_endpoint:471 calling endpoint failed due to: received_payload_not_json`.

When we return `{ "result": "ok" }`, then it is proceeded without any error. So docs doesnot follow the implementation.

**Comment by whisper-bye** [comment]
+1

**Comment by larshesel** [comment]
This repo is deprecated and the webhook pluing is part of the vernemq/vernemq repo. Also consult https://docs.vernemq.com/ for up to date information on the webhooks plugin.
