### ISSUE TITLE
auth_on_register username/password are "undefined"

### ISSUE THREAD

**Issue by baranga** [erlio/vmq_webhooks#9]
Username/password parameter in auth_on_register hook are strings with value "undefined" if connecting client doesn't send username/password.

How can I distinguish between client send nothing and client really send "undefined" as username/password? Maybe a empty username/password should be represented by empty string or false.

(see [vmq_diversity#5](https://github.com/erlio/vmq_diversity/issues/5))

**Comment by larshesel** [comment]
Hi, currently you can't.

Empty password / username are AFAICT legal MQTT credentials, so I think the right thing would be to use false instead which can be properly encoded as JSON.

**Comment by larshesel** [comment]
Hi @baranga we just merged a fix for this onto master. Undefined username/passwords are now passed as the json value 'null'.

I hope this solves your problem.
